import path from 'node:path'
import fs from 'node:fs'

const componentDir = path.resolve(__dirname, './src/components/lib')

function resolve(dir) {
  return path.join(componentDir, dir)
}

const STYLE_ALIAS = {
  'primevue2/base/style': resolve('base/style/BaseStyle.js'),
  'primevue2/basecomponent/style': resolve('basecomponent/style/BaseComponentStyle.js'),
  'primevue2/accordion/style': resolve('accordion/style/AccordionStyle.js'),
  'primevue2/accordiontab/style': resolve('accordiontab/style/AccordionTabStyle.js'),
  'primevue2/animateonscroll/style': resolve('animateonscroll/style/AnimateOnScrollStyle.js'),
  'primevue2/autocomplete/style': resolve('autocomplete/style/AutoCompleteStyle.js'),
  'primevue2/avatar/style': resolve('avatar/style/AvatarStyle.js'),
  'primevue2/avatargroup/style': resolve('avatargroup/style/AvatarGroupStyle.js'),
  'primevue2/badge/style': resolve('badge/style/BadgeStyle.js'),
  'primevue2/badgedirective/style': resolve('badgedirective/style/BadgeDirectiveStyle.js'),
  'primevue2/baseicon/style': resolve('baseicon/style/BaseIconStyle.js'),
  'primevue2/blockui/style': resolve('blockui/style/BlockUIStyle.js'),
  'primevue2/breadcrumb/style': resolve('breadcrumb/style/BreadcrumbStyle.js'),
  'primevue2/button/style': resolve('button/style/ButtonStyle.js'),
  'primevue2/buttongroup/style': resolve('buttongroup/style/ButtonGroupStyle.js'),
  'primevue2/calendar/style': resolve('calendar/style/CalendarStyle.js'),
  'primevue2/card/style': resolve('card/style/CardStyle.js'),
  'primevue2/carousel/style': resolve('carousel/style/CarouselStyle.js'),
  'primevue2/cascadeselect/style': resolve('cascadeselect/style/CascadeSelectStyle.js'),
  'primevue2/chart/style': resolve('chart/style/ChartStyle.js'),
  'primevue2/checkbox/style': resolve('checkbox/style/CheckboxStyle.js'),
  'primevue2/chip/style': resolve('chip/style/ChipStyle.js'),
  'primevue2/chips/style': resolve('chips/style/ChipsStyle.js'),
  'primevue2/colorpicker/style': resolve('colorpicker/style/ColorPickerStyle.js'),
  'primevue2/column/style': resolve('column/style/ColumnStyle.js'),
  'primevue2/columngroup/style': resolve('columngroup/style/ColumnGroupStyle.js'),
  'primevue2/confirmdialog/style': resolve('confirmdialog/style/ConfirmDialogStyle.js'),
  'primevue2/confirmpopup/style': resolve('confirmpopup/style/ConfirmPopupStyle.js'),
  'primevue2/contextmenu/style': resolve('contextmenu/style/ContextMenuStyle.js'),
  'primevue2/datatable/style': resolve('datatable/style/DataTableStyle.js'),
  'primevue2/dataview/style': resolve('dataview/style/DataViewStyle.js'),
  'primevue2/dataviewlayoutoptions/style': resolve('dataviewlayoutoptions/style/DataViewLayoutOptionsStyle.js'),
  'primevue2/deferredcontent/style': resolve('deferredcontent/style/DeferredContentStyle.js'),
  'primevue2/dialog/style': resolve('dialog/style/DialogStyle.js'),
  'primevue2/divider/style': resolve('divider/style/DividerStyle.js'),
  'primevue2/dock/style': resolve('dock/style/DockStyle.js'),
  'primevue2/dropdown/style': resolve('dropdown/style/DropdownStyle.js'),
  'primevue2/dynamicdialog/style': resolve('dynamicdialog/style/DynamicDialogStyle.js'),
  'primevue2/editor/style': resolve('editor/style/EditorStyle.js'),
  'primevue2/fieldset/style': resolve('fieldset/style/FieldsetStyle.js'),
  'primevue2/floatlabel/style': resolve('floatlabel/style/FloatLabelStyle.js'),
  'primevue2/fileupload/style': resolve('fileupload/style/FileUploadStyle.js'),
  'primevue2/focustrap/style': resolve('focustrap/style/FocusTrapStyle.js'),
  'primevue2/galleria/style': resolve('galleria/style/GalleriaStyle.js'),
  'primevue2/imagepreview/style': resolve('imagepreview/style/ImagePreviewStyle.js'),
  'primevue2/iconfield/style': resolve('iconfield/style/IconFieldStyle.js'),
  'primevue2/inlinemessage/style': resolve('inlinemessage/style/InlineMessageStyle.js'),
  'primevue2/inplace/style': resolve('inplace/style/InplaceStyle.js'),
  'primevue2/inputgroup/style': resolve('inputgroup/style/InputGroupStyle.js'),
  'primevue2/inputgroupaddon/style': resolve('inputgroupaddon/style/InputGroupAddonStyle.js'),
  'primevue2/inputicon/style': resolve('inputicon/style/InputIconStyle.js'),
  'primevue2/inputmask/style': resolve('inputmask/style/InputMaskStyle.js'),
  'primevue2/inputnumber/style': resolve('inputnumber/style/InputNumberStyle.js'),
  'primevue2/inputotp/style': resolve('inputotp/style/InputOtpStyle.js'),
  'primevue2/inputswitch/style': resolve('inputswitch/style/InputSwitchStyle.js'),
  'primevue2/inputtext/style': resolve('inputtext/style/InputTextStyle.js'),
  'primevue2/knob/style': resolve('knob/style/KnobStyle.js'),
  'primevue2/listbox/style': resolve('listbox/style/ListboxStyle.js'),
  'primevue2/megamenu/style': resolve('megamenu/style/MegaMenuStyle.js'),
  'primevue2/menu/style': resolve('menu/style/MenuStyle.js'),
  'primevue2/menubar/style': resolve('menubar/style/MenubarStyle.js'),
  'primevue2/message/style': resolve('message/style/MessageStyle.js'),
  'primevue2/metergroup/style': resolve('metergroup/style/MeterGroupStyle.js'),
  'primevue2/multiselect/style': resolve('multiselect/style/MultiSelectStyle.js'),
  'primevue2/orderlist/style': resolve('orderlist/style/OrderListStyle.js'),
  'primevue2/organizationchart/style': resolve('organizationchart/style/OrganizationChartStyle.js'),
  'primevue2/overlaypanel/style': resolve('overlaypanel/style/OverlayPanelStyle.js'),
  'primevue2/paginator/style': resolve('paginator/style/PaginatorStyle.js'),
  'primevue2/panel/style': resolve('panel/style/PanelStyle.js'),
  'primevue2/panelmenu/style': resolve('panelmenu/style/PanelMenuStyle.js'),
  'primevue2/password/style': resolve('password/style/PasswordStyle.js'),
  'primevue2/picklist/style': resolve('picklist/style/PickListStyle.js'),
  'primevue2/portal/style': resolve('portal/style/PortalStyle.js'),
  'primevue2/progressbar/style': resolve('progressbar/style/ProgressBarStyle.js'),
  'primevue2/progressspinner/style': resolve('progressspinner/style/ProgressSpinnerStyle.js'),
  'primevue2/radiobutton/style': resolve('radiobutton/style/RadioButtonStyle.js'),
  'primevue2/rating/style': resolve('rating/style/RatingStyle.js'),
  'primevue2/ripple/style': resolve('ripple/style/RippleStyle.js'),
  'primevue2/row/style': resolve('row/style/RowStyle.js'),
  'primevue2/scrollpanel/style': resolve('scrollpanel/style/ScrollPanelStyle.js'),
  'primevue2/scrolltop/style': resolve('scrolltop/style/ScrollTopStyle.js'),
  'primevue2/selectbutton/style': resolve('selectbutton/style/SelectButtonStyle.js'),
  'primevue2/sidebar/style': resolve('sidebar/style/SidebarStyle.js'),
  'primevue2/skeleton/style': resolve('skeleton/style/SkeletonStyle.js'),
  'primevue2/slider/style': resolve('slider/style/SliderStyle.js'),
  'primevue2/speeddial/style': resolve('speeddial/style/SpeedDialStyle.js'),
  'primevue2/splitbutton/style': resolve('splitbutton/style/SplitButtonStyle.js'),
  'primevue2/splitter/style': resolve('splitter/style/SplitterStyle.js'),
  'primevue2/splitterpanel/style': resolve('splitterpanel/style/SplitterPanelStyle.js'),
  'primevue2/steps/style': resolve('steps/style/StepsStyle.js'),
  'primevue2/stepper/style': resolve('stepper/style/StepperStyle.js'),
  'primevue2/stepperpanel/style': resolve('stepperpanel/style/StepperPanelStyle.js'),
  'primevue2/tabmenu/style': resolve('tabmenu/style/TabMenuStyle.js'),
  'primevue2/tabpanel/style': resolve('tabpanel/style/TabPanelStyle.js'),
  'primevue2/tabview/style': resolve('tabview/style/TabViewStyle.js'),
  'primevue2/tag/style': resolve('tag/style/TagStyle.js'),
  'primevue2/terminal/style': resolve('terminal/style/TerminalStyle.js'),
  'primevue2/textarea/style': resolve('textarea/style/TextareaStyle.js'),
  'primevue2/tieredmenu/style': resolve('tieredmenu/style/TieredMenuStyle.js'),
  'primevue2/timeline/style': resolve('timeline/style/TimelineStyle.js'),
  'primevue2/toast/style': resolve('toast/style/ToastStyle.js'),
  'primevue2/togglebutton/style': resolve('togglebutton/style/ToggleButtonStyle.js'),
  'primevue2/toolbar/style': resolve('toolbar/style/ToolbarStyle.js'),
  'primevue2/tooltip/style': resolve('tooltip/style/TooltipStyle.js'),
  'primevue2/tree/style': resolve('tree/style/TreeStyle.js'),
  'primevue2/treeselect/style': resolve('treeselect/style/TreeSelectStyle.js'),
  'primevue2/treetable/style': resolve('treetable/style/TreeTableStyle.js'),
  'primevue2/tristatecheckbox/style': resolve('tristatecheckbox/style/TriStateCheckboxStyle.js'),
  'primevue2/virtualscroller/style': resolve('virtualscroller/style/VirtualScrollerStyle.js')
}

const ICON_ALIAS = {
  'primevue2/baseicon': resolve('baseicon/BaseIcon.vue'),
  'primevue2/icons/angledoubledown': resolve('icons/angledoubledown/index.vue'),
  'primevue2/icons/angledoubleleft': resolve('icons/angledoubleleft/index.vue'),
  'primevue2/icons/angledoubleright': resolve('icons/angledoubleright/index.vue'),
  'primevue2/icons/angledoubleup': resolve('icons/angledoubleup/index.vue'),
  'primevue2/icons/angledown': resolve('icons/angledown/index.vue'),
  'primevue2/icons/angleleft': resolve('icons/angleleft/index.vue'),
  'primevue2/icons/angleright': resolve('icons/angleright/index.vue'),
  'primevue2/icons/angleup': resolve('icons/angleup/index.vue'),
  'primevue2/icons/arrowdown': resolve('icons/arrowdown/index.vue'),
  'primevue2/icons/arrowup': resolve('icons/arrowup/index.vue'),
  'primevue2/icons/ban': resolve('icons/ban/index.vue'),
  'primevue2/icons/bars': resolve('icons/bars/index.vue'),
  'primevue2/icons/blank': resolve('icons/blank/index.vue'),
  'primevue2/icons/calendar': resolve('icons/calendar/index.vue'),
  'primevue2/icons/check': resolve('icons/check/index.vue'),
  'primevue2/icons/chevrondown': resolve('icons/chevrondown/index.vue'),
  'primevue2/icons/chevronleft': resolve('icons/chevronleft/index.vue'),
  'primevue2/icons/chevronright': resolve('icons/chevronright/index.vue'),
  'primevue2/icons/chevronup': resolve('icons/chevronup/index.vue'),
  'primevue2/icons/exclamationtriangle': resolve('icons/exclamationtriangle/index.vue'),
  'primevue2/icons/eye': resolve('icons/eye/index.vue'),
  'primevue2/icons/eyeslash': resolve('icons/eyeslash/index.vue'),
  'primevue2/icons/filter': resolve('icons/filter/index.vue'),
  'primevue2/icons/filterslash': resolve('icons/filterslash/index.vue'),
  'primevue2/icons/infocircle': resolve('icons/infocircle/index.vue'),
  'primevue2/icons/minus': resolve('icons/minus/index.vue'),
  'primevue2/icons/pencil': resolve('icons/pencil/index.vue'),
  'primevue2/icons/plus': resolve('icons/plus/index.vue'),
  'primevue2/icons/refresh': resolve('icons/refresh/index.vue'),
  'primevue2/icons/search': resolve('icons/search/index.vue'),
  'primevue2/icons/searchminus': resolve('icons/searchminus/index.vue'),
  'primevue2/icons/searchplus': resolve('icons/searchplus/index.vue'),
  'primevue2/icons/sortalt': resolve('icons/sortalt/index.vue'),
  'primevue2/icons/sortamountdown': resolve('icons/sortamountdown/index.vue'),
  'primevue2/icons/sortamountupalt': resolve('icons/sortamountupalt/index.vue'),
  'primevue2/icons/spinner': resolve('icons/spinner/index.vue'),
  'primevue2/icons/star': resolve('icons/star/index.vue'),
  'primevue2/icons/starfill': resolve('icons/starfill/index.vue'),
  'primevue2/icons/thlarge': resolve('icons/thlarge/index.vue'),
  'primevue2/icons/times': resolve('icons/times/index.vue'),
  'primevue2/icons/timescircle': resolve('icons/timescircle/index.vue'),
  'primevue2/icons/trash': resolve('icons/trash/index.vue'),
  'primevue2/icons/undo': resolve('icons/undo/index.vue'),
  'primevue2/icons/upload': resolve('icons/upload/index.vue'),
  'primevue2/icons/windowmaximize': resolve('icons/windowmaximize/index.vue'),
  'primevue2/icons/windowminimize': resolve('icons/windowminimize/index.vue')
}

const ALL_ALIAS =  {
  '@': path.resolve(__dirname, 'src'),
  'lib': path.resolve(__dirname, 'lib'),
  'primevue2/config': resolve('config/PrimeVue.js'),
  'primevue2/utils': resolve('utils/Utils.js'),
  'primevue2/api': resolve('api/Api.js'),
  ...STYLE_ALIAS,
  'primevue2/base': resolve('base/Base.js'),
  'primevue2/basedirective': resolve('basedirective/BaseDirective.js'),
  'primevue2/ripple': resolve('ripple/Ripple.js'),
  'primevue2/tooltip': resolve('tooltip/Tooltip.js'),
  'primevue2/focustrap': resolve('focustrap/FocusTrap.js'),
  'primevue2/useconfirm': resolve('useconfirm/UseConfirm.js'),
  'primevue2/usetoast': resolve('usetoast/UseToast.js'),
  'primevue2/usedialog': resolve('usedialog/UseDialog.js'),
  'primevue2/usestyle': resolve('usestyle/UseStyle.js'),
  'primevue2/teleport': resolve('teleport/Teleport.vue'),
  'primevue2/portal': resolve('portal/Portal.vue'),
  'primevue2/basecomponent': resolve('basecomponent/BaseComponent.vue'),
  ...ICON_ALIAS,
  'primevue2/button': resolve('button/Button.vue'),
  'primevue2/inputtext': resolve('inputtext/InputText.vue'),
  'primevue2/checkbox': resolve('checkbox/Checkbox.vue'),
  'primevue2/radiobutton': resolve('radiobutton/RadioButton.vue'),
  'primevue2/dialog': resolve('dialog/Dialog.vue'),
  'primevue2/menu': resolve('menu/Menu.vue'),
  'primevue2/tieredmenu': resolve('tieredmenu/TieredMenu.vue'),
  'primevue2/dropdown': resolve('dropdown/Dropdown.vue'),
  'primevue2/inputnumber': resolve('inputnumber/InputNumber.vue'),
  'primevue2/paginator': resolve('paginator/Paginator.vue'),
  'primevue2/progressbar': resolve('progressbar/ProgressBar.vue'),
  'primevue2/message': resolve('message/Message.vue'),
  'primevue2/tree': resolve('tree/Tree.vue'),
  'primevue2/badge': resolve('badge/Badge.vue'),
  'primevue2/confirmationeventbus': resolve('confirmationeventbus/ConfirmationEventBus.js'),
  'primevue2/toasteventbus': resolve('toasteventbus/ToastEventBus.js'),
  'primevue2/overlayeventbus': resolve('overlayeventbus/OverlayEventBus.js'),
  'primevue2/terminalservice': resolve('terminalservice/TerminalService.js'),
  'primevue2/dynamicdialogeventbus': resolve('dynamicdialogeventbus/DynamicDialogEventBus.js'),
  'primevue2/virtualscroller': resolve('virtualscroller/VirtualScroller.vue'),
  'primevue2/passthrough': resolve('passthrough/index.js'),
  'primevue2/passthrough/tailwind': resolve('passthrough/tailwind/index.js')
}

// src/components中使用了 'primevue2/xx'，需要设置别名
fs.readdirSync(componentDir, { withFileTypes: true })
  .filter((dir) => dir.isDirectory())
  .forEach(({ name: folderName }) => {
    const folderPath = path.join(componentDir, folderName)

    fs.readdirSync(folderPath, { withFileTypes: true }).forEach((file) => {
      const name = file.name.split(/(.vue)$|(.js)$/)[0].toLowerCase()
      if (name === folderName) {
        ALL_ALIAS[path.join('primevue2', name)] = resolve(path.join(folderName, file.name))
      }
    })
  })

console.log('primevue2/autocomplete', ALL_ALIAS['primevue2/autocomplete'])
export default ALL_ALIAS
